{
    "msg": "返回成功",
    "muban": [
        {
            "ename": "ay",
            "cunt": 21,
            "grade": "1.0",
            "cname": "A1型题",
            "shiti": [
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "利多卡因治疗心律失常的主要机制是",
                    "discription": "利多卡因属I B类抗心律失常药。对心肌的直接作用是抑Na<sup>+</sup>内流，促K<sup>+</sup>外流。\n    但对心房及窦房结作用很轻。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0116_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "A",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "阻滞钙通道",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "阻滞β受体",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "阻滞α受体",
                    "fourth": "阻滞钾通道",
                    "answerPic": "",
                    "first": "阻滞钠通道"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "口服补液盐中加入葡萄糖的主要作用是",
                    "discription": "静脉补液非电解质溶液：常用5％或10％葡萄糖溶液，主要供给水分和供应部分能量，5％葡萄糖溶液为等渗液，10％葡萄糖溶液为高渗液，因葡萄糖输入体内将被氧化分解咸水，没有维持血浆渗透压的作用，故属无张力液。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0117_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "降低血清钾浓度",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "预防酮症酸中毒",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "增加肠道对水、钠重吸收",
                    "fourth": "补充电解质",
                    "answerPic": "",
                    "first": "使口服补液盐具有一定的渗透压"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "子宫内膜异位症患者卵巢病变最常见的类型是",
                    "discription": "",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0118_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "E",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "卵巢黄体囊肿",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "卵巢滤泡囊肿",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "卵巢巧克力囊肿",
                    "fourth": "卵巢炎性包块",
                    "answerPic": "",
                    "first": "卵巢恶性肿瘤"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "产后血性恶露持续的时间一般是",
                    "discription": "(1)血性恶露：持续3～4天，出血量逐渐减少，浆液增加，转变为浆液恶露。\n    (2)浆液恶露：持续10天左右，浆液逐渐减少，白细胞增多，变为白色恶露。\n    (3)白色恶露：持续3周干净。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0124_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "3～4天",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "8～10天",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "15～20天",
                    "fourth": "10～15天",
                    "answerPic": "",
                    "first": "1～2天"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "导致COPD最常见的因素是",
                    "discription": "吸烟为慢性阻塞性肺疾病重要的发病因素，烟草中含焦油、尼古丁和氢氰酸等化学物质，可损伤气道上皮细胞，可使支气管痉挛，呼吸道上皮细胞纤毛运动受抑制，纤毛脱落，而易致感染。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0125_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "A",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "职业粉尘",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "大气污染",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "蛋白酶-抗蛋白酶失调",
                    "fourth": "感染",
                    "answerPic": "",
                    "first": "吸烟"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "以下现病史符合新生儿病理性黄疸的是",
                    "discription": "病理性黄疸：\n    (1)生后24小时内出现黄疸；\n    (2)血清胆红素足月儿＞221μmol／L(12．9mg／dl)，早产儿＞257μmol／L(15mg／dl)或每日上升＞85μmol／L(5mg／dl)；\n    (3)黄疸持续时间足月儿大于2周，早产儿大于4周；\n    (4)黄疸退而复现；\n    (5)血清结合胆红素＞34μmol／L(2mg／dl)。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0129_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "生后24小时内出现黄疸",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "黄疸持续时间足月儿大于1周",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "早产儿血清胆红素＜275μmol／l(15mgdl)",
                    "fourth": "足月儿血清胆红素＜221μmol／／l(12．9mg/dl)",
                    "answerPic": "",
                    "first": "血清总胆红素逐渐加重，每日上升2mg/dl"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "当中心静脉压小于2～5cmH<sub>2</sub>O时，常提示的是",
                    "discription": "中心静脉压正常值为5～12cmHsub>2</sub>O，其反应右心房压力。若中心静脉压小于5cmHsub>2</sub>O，为右心房充盈不足或血容量不足。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0131_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "右心功能不良",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "右心房充盈不佳或血容量不足",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "左心功能不良",
                    "fourth": "血容量过多",
                    "answerPic": "",
                    "first": "左心房充盈不佳或血容量不足"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "肾结核的原发病灶多在",
                    "discription": "肾结核是泌尿系统疾病中的常见病。它是全身结核病的一部分，约占结核病的8％～20％。肾结核大多继发于肺结核，结核杆菌是经血行进入肾脏，形成结核病灶。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0133_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "肺",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "肠",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "脑",
                    "fourth": "肝",
                    "answerPic": "",
                    "first": "骨"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "护士在为患者作入院介绍，此时护患关系是",
                    "discription": "护患关系的发展过程护患关系的发展是一个动态的过程，一般分为初始期、工作期和结束期三个阶段。初始期：亦称熟悉期，是护士与患者的初识阶段，也是护患之间开始建立信任关系的时期。此期的工作重点是建立信任关系，确认患者的需要。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0134_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "A",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "结束期",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "工作期",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "熟悉期",
                    "fourth": "准备期",
                    "answerPic": "",
                    "first": "初始期"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "ARDS患者最容易出现的心理问题是",
                    "discription": "",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0137_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "焦虑",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "恐惧",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "抑郁",
                    "fourth": "绝望",
                    "answerPic": "",
                    "first": "孤独感"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "明确蛛网膜下腔出血病因的最有效检查方法是",
                    "discription": "脑血管病是指脑血管病变所引起的脑功能障碍。按病变性质可分出血性脑血管病和缺血性脑血管病两大类。前者包括脑出血、蛛网膜下腔出血；后者包括有短暂性脑缺血发作、脑血栓形成、脑栓塞。CT、MRI在脑血管疾病诊断方面CT能够作出早期诊断，准确的鉴别诊断，并能直接显示出病变部位、范围和出血数量。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0140_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "血管造影",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "CT",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "核磁共振",
                    "fourth": "腰穿",
                    "answerPic": "",
                    "first": "头部彩超"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "急性上呼吸道感染最常见的病原体是",
                    "discription": "急性上呼吸道感染70％～80％是病毒引起，其中包括鼻病毒，流感病毒，副流感病毒，呼吸道合胞病毒，腺病毒，埃可病毒，柯萨奇病毒等；细菌感染约占20％～30％。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0144_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "病毒",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "真菌",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "葡萄球菌",
                    "fourth": "支原体",
                    "answerPic": "",
                    "first": "细菌"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "腹外疝患者因担心疝块反复突出影响工作和生活，最常产生的主要心理问题是",
                    "discription": "",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0147_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "忧郁",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "焦虑",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "愤怒",
                    "fourth": "恐惧",
                    "answerPic": "",
                    "first": "自卑"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "轻型急性胰腺炎患者开始进食无脂低蛋白饮食的时间为患者病后",
                    "discription": "多数急性胰腺炎患者需要禁食1～3天，减少胃酸与食物刺激胰液分泌。明显腹胀的患者应进行胃肠减压，减轻呕吐与腹胀。轻症胰腺炎经过3～5天禁食和胃肠减压，当疼痛减轻，发热消退，白细胞计数和血、尿淀粉酶降至正常后即可给予少量无脂饮食。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0148_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "不超过12小时",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "5～7天",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "1～3天",
                    "fourth": "7天以上",
                    "answerPic": "",
                    "first": "3～5天"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "关于二甲双胍治疗糖尿病的叙述，错误的是",
                    "discription": "双胍类：对胰岛无刺激作用，主要通过增加外周组织对葡萄糖的摄取和利用，抑制葡萄糖异生及肝糖原分解而起降低血糖作用。最适合超重的2型糖尿病。通常每天用量500～1500mg，分2～3次口服，最大剂量不超过2g。不良反应：\n    (1)偶见恶心、呕吐、腹泻、腹痛、腹胀、消化不良、乏力等。\n    (2)偶有疲倦、体重减轻、头痛、头晕、味觉异常、皮疹、寒战、流感样症状、心悸、潮红等现象。\n    (3)罕见乳酸性酸中毒，表现为呕吐、腹痛、过度换气、意识障碍。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0151_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "服用时应与第一口饭同时咀嚼",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "可改善胰岛素敏感性，减轻胰岛素抵抗",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "治疗肥胖或超重的2型糖尿病的首选药",
                    "fourth": "可导致腹部不适、恶心、腹泻等不良反应",
                    "answerPic": "",
                    "first": "每天最大剂量不应超过2g"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "胸部外伤后出现胸廓软化是由于",
                    "discription": "多根多处肋骨骨折会使局部胸壁失去支撑软化，出现反常呼吸运动。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0156_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "D",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "胸骨骨折",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "锁骨骨折",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "胸肌大面积损伤",
                    "fourth": "多根多段肋骨骨折",
                    "answerPic": "",
                    "first": "一根肋骨多处骨折"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "甲硝唑用于治疗阿米巴性肝脓肿时，最常出现的不良反应是",
                    "discription": "甲硝唑不良反应中消化道反应最为常见，包括恶心、呕吐、食欲不振、腹部绞痛，一般不影响治疗。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0158_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "荨麻疹",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "恶心、呕吐",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "头痛、眩晕",
                    "fourth": "白细胞减少",
                    "answerPic": "",
                    "first": "急性膀胱炎"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "急性呼吸窘迫综合征早期的病理变化不包括",
                    "discription": "(1)呼吸窘迫综合征(ARDS)生理改变：在炎性细胞和炎症介质的作用下，导致肺毛细血管内皮细胞和肺泡上皮细胞损伤，肺泡通透性增加，使毛细血管管内液体和蛋白质漏入肺间质和肺泡，引起肺间质和肺泡水肿。肺泡大量积水又可使肺泡表面物质减少，出现小气道陷闭和肺泡萎陷。\n    (2)ARDS病理改变：ARDS的主要病理改变是肺广泛性充血、水肿、肺泡透明膜的形成。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0161_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "E",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "肺泡萎陷",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "肺泡内透明膜形成",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "肺泡纤维化",
                    "fourth": "肺充血",
                    "answerPic": "",
                    "first": "肺间质水肿"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "关于肝硬化门脉高压患者的临床表现，错误的叙述是",
                    "discription": "门静脉高压的临床表现是脾大、侧支循环建立和开放、腹水。侧支循环建立和开放有食管下段和胃底静脉曲张。腹壁静脉曲张、痔核形成三个重要的侧支循环建立。全身都有出血的危险。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0162_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "全身无出血倾向",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "可出现黄疸、蜘蛛痣、腹壁静脉曲张等",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "门静脉血液阻力增加是门脉高压的始动因素",
                    "fourth": "腹部膨隆，可叩出腹部移动性浊音",
                    "answerPic": "",
                    "first": "早期可出现脾大，脾功能亢进"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "目前确诊慢性胃炎最可靠的方法是",
                    "discription": "胃镜检查是确诊慢性胃炎最可靠的确诊方法。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0163_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "D",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "血清抗体测定",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "胃肠钡餐检查",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "幽门螺杆菌检测",
                    "fourth": "纤维胃镜检查",
                    "answerPic": "",
                    "first": "胃液分析"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "颅内压增高的典型临床表现是",
                    "discription": "头痛、呕吐和视神经乳头水肿是颅内压增高的典型表现。头痛是颅内压增高最常见的症状，常在晨起或夜间时出现，咳嗽、低头、用力时加重，头痛部位常在前额、两侧颞部。呕吐常在头痛剧烈时出现，呈喷射性，可伴有恶心，与进食无直接关系。视神经乳头水肿是颅内压增高的重要客观体征，常为双侧性。早期多不影响视力，存在时间较久者有视力减退，严重者失明。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0164_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "D",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "头疼、呕吐、感觉障碍",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "头疼、抽搐、血压增高",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "头疼、抽搐、昏迷",
                    "fourth": "头疼、呕吐、视神经乳头水肿",
                    "answerPic": "",
                    "first": "头疼、抽搐、偏瘫"
                }
            ],
            "basic": "1"
        },
        {
            "ename": "ay",
            "cunt": 21,
            "grade": "1.0",
            "cname": "A1型题/单选题",
            "shiti": [
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "利多卡因治疗心律失常的主要机制是",
                    "discription": "利多卡因属I B类抗心律失常药。对心肌的直接作用是抑Na<sup>+</sup>内流，促K<sup>+</sup>外流。\n    但对心房及窦房结作用很轻。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0116_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "A",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "阻滞钙通道",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "阻滞β受体",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "阻滞α受体",
                    "fourth": "阻滞钾通道",
                    "answerPic": "",
                    "first": "阻滞钠通道"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "口服补液盐中加入葡萄糖的主要作用是",
                    "discription": "静脉补液非电解质溶液：常用5％或10％葡萄糖溶液，主要供给水分和供应部分能量，5％葡萄糖溶液为等渗液，10％葡萄糖溶液为高渗液，因葡萄糖输入体内将被氧化分解咸水，没有维持血浆渗透压的作用，故属无张力液。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0117_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "降低血清钾浓度",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "预防酮症酸中毒",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "增加肠道对水、钠重吸收",
                    "fourth": "补充电解质",
                    "answerPic": "",
                    "first": "使口服补液盐具有一定的渗透压"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "子宫内膜异位症患者卵巢病变最常见的类型是",
                    "discription": "",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0118_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "E",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "卵巢黄体囊肿",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "卵巢滤泡囊肿",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "卵巢巧克力囊肿",
                    "fourth": "卵巢炎性包块",
                    "answerPic": "",
                    "first": "卵巢恶性肿瘤"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "产后血性恶露持续的时间一般是",
                    "discription": "(1)血性恶露：持续3～4天，出血量逐渐减少，浆液增加，转变为浆液恶露。\n    (2)浆液恶露：持续10天左右，浆液逐渐减少，白细胞增多，变为白色恶露。\n    (3)白色恶露：持续3周干净。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0124_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "3～4天",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "8～10天",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "15～20天",
                    "fourth": "10～15天",
                    "answerPic": "",
                    "first": "1～2天"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "导致COPD最常见的因素是",
                    "discription": "吸烟为慢性阻塞性肺疾病重要的发病因素，烟草中含焦油、尼古丁和氢氰酸等化学物质，可损伤气道上皮细胞，可使支气管痉挛，呼吸道上皮细胞纤毛运动受抑制，纤毛脱落，而易致感染。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0125_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "A",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "职业粉尘",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "大气污染",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "蛋白酶-抗蛋白酶失调",
                    "fourth": "感染",
                    "answerPic": "",
                    "first": "吸烟"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "以下现病史符合新生儿病理性黄疸的是",
                    "discription": "病理性黄疸：\n    (1)生后24小时内出现黄疸；\n    (2)血清胆红素足月儿＞221μmol／L(12．9mg／dl)，早产儿＞257μmol／L(15mg／dl)或每日上升＞85μmol／L(5mg／dl)；\n    (3)黄疸持续时间足月儿大于2周，早产儿大于4周；\n    (4)黄疸退而复现；\n    (5)血清结合胆红素＞34μmol／L(2mg／dl)。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0129_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "生后24小时内出现黄疸",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "黄疸持续时间足月儿大于1周",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "早产儿血清胆红素＜275μmol／l(15mgdl)",
                    "fourth": "足月儿血清胆红素＜221μmol／／l(12．9mg/dl)",
                    "answerPic": "",
                    "first": "血清总胆红素逐渐加重，每日上升2mg/dl"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "当中心静脉压小于2～5cmH<sub>2</sub>O时，常提示的是",
                    "discription": "中心静脉压正常值为5～12cmHsub>2</sub>O，其反应右心房压力。若中心静脉压小于5cmHsub>2</sub>O，为右心房充盈不足或血容量不足。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0131_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "右心功能不良",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "右心房充盈不佳或血容量不足",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "左心功能不良",
                    "fourth": "血容量过多",
                    "answerPic": "",
                    "first": "左心房充盈不佳或血容量不足"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "肾结核的原发病灶多在",
                    "discription": "肾结核是泌尿系统疾病中的常见病。它是全身结核病的一部分，约占结核病的8％～20％。肾结核大多继发于肺结核，结核杆菌是经血行进入肾脏，形成结核病灶。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0133_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "肺",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "肠",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "脑",
                    "fourth": "肝",
                    "answerPic": "",
                    "first": "骨"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "护士在为患者作入院介绍，此时护患关系是",
                    "discription": "护患关系的发展过程护患关系的发展是一个动态的过程，一般分为初始期、工作期和结束期三个阶段。初始期：亦称熟悉期，是护士与患者的初识阶段，也是护患之间开始建立信任关系的时期。此期的工作重点是建立信任关系，确认患者的需要。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0134_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "A",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "结束期",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "工作期",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "熟悉期",
                    "fourth": "准备期",
                    "answerPic": "",
                    "first": "初始期"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "ARDS患者最容易出现的心理问题是",
                    "discription": "",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0137_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "焦虑",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "恐惧",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "抑郁",
                    "fourth": "绝望",
                    "answerPic": "",
                    "first": "孤独感"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "明确蛛网膜下腔出血病因的最有效检查方法是",
                    "discription": "脑血管病是指脑血管病变所引起的脑功能障碍。按病变性质可分出血性脑血管病和缺血性脑血管病两大类。前者包括脑出血、蛛网膜下腔出血；后者包括有短暂性脑缺血发作、脑血栓形成、脑栓塞。CT、MRI在脑血管疾病诊断方面CT能够作出早期诊断，准确的鉴别诊断，并能直接显示出病变部位、范围和出血数量。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0140_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "血管造影",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "CT",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "核磁共振",
                    "fourth": "腰穿",
                    "answerPic": "",
                    "first": "头部彩超"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "急性上呼吸道感染最常见的病原体是",
                    "discription": "急性上呼吸道感染70％～80％是病毒引起，其中包括鼻病毒，流感病毒，副流感病毒，呼吸道合胞病毒，腺病毒，埃可病毒，柯萨奇病毒等；细菌感染约占20％～30％。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0144_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "病毒",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "真菌",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "葡萄球菌",
                    "fourth": "支原体",
                    "answerPic": "",
                    "first": "细菌"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "腹外疝患者因担心疝块反复突出影响工作和生活，最常产生的主要心理问题是",
                    "discription": "",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0147_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "忧郁",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "焦虑",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "愤怒",
                    "fourth": "恐惧",
                    "answerPic": "",
                    "first": "自卑"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "轻型急性胰腺炎患者开始进食无脂低蛋白饮食的时间为患者病后",
                    "discription": "多数急性胰腺炎患者需要禁食1～3天，减少胃酸与食物刺激胰液分泌。明显腹胀的患者应进行胃肠减压，减轻呕吐与腹胀。轻症胰腺炎经过3～5天禁食和胃肠减压，当疼痛减轻，发热消退，白细胞计数和血、尿淀粉酶降至正常后即可给予少量无脂饮食。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0148_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "不超过12小时",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "5～7天",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "1～3天",
                    "fourth": "7天以上",
                    "answerPic": "",
                    "first": "3～5天"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "关于二甲双胍治疗糖尿病的叙述，错误的是",
                    "discription": "双胍类：对胰岛无刺激作用，主要通过增加外周组织对葡萄糖的摄取和利用，抑制葡萄糖异生及肝糖原分解而起降低血糖作用。最适合超重的2型糖尿病。通常每天用量500～1500mg，分2～3次口服，最大剂量不超过2g。不良反应：\n    (1)偶见恶心、呕吐、腹泻、腹痛、腹胀、消化不良、乏力等。\n    (2)偶有疲倦、体重减轻、头痛、头晕、味觉异常、皮疹、寒战、流感样症状、心悸、潮红等现象。\n    (3)罕见乳酸性酸中毒，表现为呕吐、腹痛、过度换气、意识障碍。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0151_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "服用时应与第一口饭同时咀嚼",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "可改善胰岛素敏感性，减轻胰岛素抵抗",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "治疗肥胖或超重的2型糖尿病的首选药",
                    "fourth": "可导致腹部不适、恶心、腹泻等不良反应",
                    "answerPic": "",
                    "first": "每天最大剂量不应超过2g"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "胸部外伤后出现胸廓软化是由于",
                    "discription": "多根多处肋骨骨折会使局部胸壁失去支撑软化，出现反常呼吸运动。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0156_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "D",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "胸骨骨折",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "锁骨骨折",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "胸肌大面积损伤",
                    "fourth": "多根多段肋骨骨折",
                    "answerPic": "",
                    "first": "一根肋骨多处骨折"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "甲硝唑用于治疗阿米巴性肝脓肿时，最常出现的不良反应是",
                    "discription": "甲硝唑不良反应中消化道反应最为常见，包括恶心、呕吐、食欲不振、腹部绞痛，一般不影响治疗。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0158_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "C",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "荨麻疹",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "恶心、呕吐",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "头痛、眩晕",
                    "fourth": "白细胞减少",
                    "answerPic": "",
                    "first": "急性膀胱炎"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "急性呼吸窘迫综合征早期的病理变化不包括",
                    "discription": "(1)呼吸窘迫综合征(ARDS)生理改变：在炎性细胞和炎症介质的作用下，导致肺毛细血管内皮细胞和肺泡上皮细胞损伤，肺泡通透性增加，使毛细血管管内液体和蛋白质漏入肺间质和肺泡，引起肺间质和肺泡水肿。肺泡大量积水又可使肺泡表面物质减少，出现小气道陷闭和肺泡萎陷。\n    (2)ARDS病理改变：ARDS的主要病理改变是肺广泛性充血、水肿、肺泡透明膜的形成。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0161_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "E",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "肺泡萎陷",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "肺泡内透明膜形成",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "肺泡纤维化",
                    "fourth": "肺充血",
                    "answerPic": "",
                    "first": "肺间质水肿"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "关于肝硬化门脉高压患者的临床表现，错误的叙述是",
                    "discription": "门静脉高压的临床表现是脾大、侧支循环建立和开放、腹水。侧支循环建立和开放有食管下段和胃底静脉曲张。腹壁静脉曲张、痔核形成三个重要的侧支循环建立。全身都有出血的危险。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0162_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "B",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "全身无出血倾向",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "可出现黄疸、蜘蛛痣、腹壁静脉曲张等",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "门静脉血液阻力增加是门脉高压的始动因素",
                    "fourth": "腹部膨隆，可叩出腹部移动性浊音",
                    "answerPic": "",
                    "first": "早期可出现脾大，脾功能亢进"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "目前确诊慢性胃炎最可靠的方法是",
                    "discription": "胃镜检查是确诊慢性胃炎最可靠的确诊方法。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0163_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "D",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "血清抗体测定",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "胃肠钡餐检查",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "幽门螺杆菌检测",
                    "fourth": "纤维胃镜检查",
                    "answerPic": "",
                    "first": "胃液分析"
                },
                {
                    "groupCodePrimQuestion": "",
                    "primQuestion": "颅内压增高的典型临床表现是",
                    "discription": "头痛、呕吐和视神经乳头水肿是颅内压增高的典型表现。头痛是颅内压增高最常见的症状，常在晨起或夜间时出现，咳嗽、低头、用力时加重，头痛部位常在前额、两侧颞部。呕吐常在头痛剧烈时出现，呈喷射性，可伴有恶心，与进食无直接关系。视神经乳头水肿是颅内压增高的重要客观体征，常为双侧性。早期多不影响视力，存在时间较久者有视力减退，严重者失明。",
                    "firstPic": "",
                    "questionCode": "id_ve09001002sjnlay1_ay_0164_19058",
                    "isCollect": "0",
                    "subPrimPic": "",
                    "refAnswer": "D",
                    "fourthPic": "",
                    "discPic": "",
                    "second": "头疼、呕吐、感觉障碍",
                    "subjectTypeEname": "ay",
                    "originalText": "",
                    "thirdPic": "",
                    "secondPic": "",
                    "third": "头疼、抽搐、血压增高",
                    "fifthPic": "",
                    "audioFiles": "",
                    "children": [],
                    "primPic": "",
                    "fifth": "头疼、抽搐、昏迷",
                    "fourth": "头疼、呕吐、视神经乳头水肿",
                    "answerPic": "",
                    "first": "头疼、抽搐、偏瘫"
                }
            ],
            "basic": "1"
        }
    ],
    "examTypeCode": "ve09001002",
    "code": 1,
    "examstyle": "5",
    "examName": "2017年5月执业护士实践能力（A1型题）上机考试真题题库（一）",
    "count": 42,
    "examID": "bb4a43c8-4917-4ee4-b0fb-3f640ad08157",
    "planID": "jia",
    "timelimit": 120
}